function [ moduleName, functionPath, functionName, parameters ] = registerMod()
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

    handles = createGUI();
    
    % main is the handle for the main GUI figure
    main = handles.main;
    
    % disable the parameters panel untill a function has been selected
    togglePanel(handles.panel_parameters, false);
    
    %TODO: MAY NOT NEED handles.output
    handles.output = [];
    
    % default values in handles
    moduleName = '';
    functionPath = '';
    functionName = '';
    parameters = struct();
    
    % save the handles struct on the main GUI figure
    guidata(main, handles);

    % don't return anything untill user has entered data and clicked
    % Install
    uiwait(main);
    
    %------------------------
    % the rest of this function runs once uiresume is called from Install
    try
        handles = guidata(main);    % get the now updated handles struct

        moduleName = handles.moduleName;
        functionPath = handles.functionPath;
        functionName = handles.functionName;
        parameters = handles.parameters;
 
       
    catch
        % exception when the GUI figure has already been deleted when 
        % uiresume gets called
    end
    
    if ishandle(handles.main)
        close(handles.main);
    end
end

function togglePanel(panel, setEnabled)
    if setEnabled
        set( findall(panel, '-property', 'Enable'), 'Enable', 'on');
    else
        set( findall(panel, '-property', 'Enable'), 'Enable', 'off');
    end
end

function button_Install_Callback(hObject, ~)

    % get the handles struct
    handles = guidata(hObject);
    
    % output a struct that contains all the module info that the user supplied
    moduleName = get(handles.edit_moduleName, 'String');
    fullFileName = get(handles.edit_fullFileName, 'String');

    if isempty(moduleName)
        choice = questdlg('Please enter a Module name.', 'Install Module', 'Ok', 'Cancel', 'Ok');
        if ~strcmp(choice, 'Ok')
            % just close the GUI
            uiresume(handles.main);
        else
            % just return to the GUI and don't continue with module
            % registration
            return;
        end
    end

    if MPBus.verifyFile(fullFileName, '.m')
        [functionPath, functionName, ~] = fileparts(fullFileName);

        handles.moduleName = moduleName;
        handles.functionPath = functionPath;
        handles.functionName = functionName;
        
        % the handles struct has been updated, save it as GUI data
        guidata(handles.main, handles);
        
        % resume will close the GUI and return data
        uiresume(handles.main);
    else
        errordlg(sprintf('The file %s could not be found.', ...
            fullFileName));
    end

end

function button_cancel_Callback(hObject, ~)
    handles = guidata(hObject);    
    uiresume(handles.main);
    delete(handles.main);   
end

function button_browse_Callback(hObject, ~)
    handles = guidata(hObject);
    [name, path] = uigetfile('*.m','open function file (*.m)');
    
    if MPBus.verifyFile([path name], '.m')
        set(handles.edit_fullFileName, 'String', [path name]);

        % now that a function has been selected, read in the function signature
        % and enable the parameters panel
        [handles.parameters.inputs, handles.parameters.outputs] = ...
                                           MPBus.readSignature(path, name);

        % a warning will occur the item currently selected in a listbox has
        % a larger value than the number of strings being set in the
        % listbox
        % for example, if the fourth string in a listbox is currently
        % selected then replacing the listbox with only 3 strings will
        % generate a warning
        set(handles.listbox_inputs, 'Value', 1);
        set(handles.listbox_outputs, 'Value', 1);
        set(handles.listbox_inputs, 'String', handles.parameters.inputs);
        set(handles.listbox_outputs, 'String', handles.parameters.outputs);
        togglePanel(handles.panel_parameters, true);
        
        % save the newly update handles struct
        guidata(hObject, handles);
    end
end






function handles = createGUI()
handles.main = figure(...
'Color',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Colormap',[0 0 0.5625;0 0 0.625;0 0 0.6875;0 0 0.75;0 0 0.8125;0 0 0.875;0 0 0.9375;0 0 1;0 0.0625 1;0 0.125 1;0 0.1875 1;0 0.25 1;0 0.3125 1;0 0.375 1;0 0.4375 1;0 0.5 1;0 0.5625 1;0 0.625 1;0 0.6875 1;0 0.75 1;0 0.8125 1;0 0.875 1;0 0.9375 1;0 1 1;0.0625 1 1;0.125 1 0.9375;0.1875 1 0.875;0.25 1 0.8125;0.3125 1 0.75;0.375 1 0.6875;0.4375 1 0.625;0.5 1 0.5625;0.5625 1 0.5;0.625 1 0.4375;0.6875 1 0.375;0.75 1 0.3125;0.8125 1 0.25;0.875 1 0.1875;0.9375 1 0.125;1 1 0.0625;1 1 0;1 0.9375 0;1 0.875 0;1 0.8125 0;1 0.75 0;1 0.6875 0;1 0.625 0;1 0.5625 0;1 0.5 0;1 0.4375 0;1 0.375 0;1 0.3125 0;1 0.25 0;1 0.1875 0;1 0.125 0;1 0.0625 0;1 0 0;0.9375 0 0;0.875 0 0;0.8125 0 0;0.75 0 0;0.6875 0 0;0.625 0 0;0.5625 0 0],...
'DockControls','off',...
'IntegerHandle','off',...
'MenuBar','none',...
'Name','Install Module',...
'NumberTitle','off',...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'Position',[544 112 489 513],...
'HandleVisibility','callback',...
'UserData',[],...
'Tag','figure1',...
'Visible','on' );


handles.panel_name = uipanel(...
'Parent',handles.main,...
'Title','Module Name',...
'Clipping','on',...
'Position',[0.05 0.81 0.90 0.14],...
'Tag','panel_name' );


handles.edit_moduleName = uicontrol(...
'Parent',handles.panel_name,...
'Units','normalized',...
'BackgroundColor',[1 1 1],...
'Position',[0.04 0.33 0.30 0.49],...
'String',blanks(0),...
'Style','edit',...
'Tag','edit_moduleName');


handles.h4 = uicontrol(...
'Parent',handles.panel_name,...
'Units','normalized',...
'Position',[0.40 0.27 0.58 0.53],...
'String','Choose a name for the module you wish to install.',...
'Style','text',...
'Tag','text15' );


handles.panel_function = uipanel(...
'Parent',handles.main,...
'Title','Function Name and Path',...
'Clipping','on',...
'Position',[0.05 0.58 0.90 0.21],...
'Tag','panel_function' );

handles.edit_fullFileName = uicontrol(...
'Parent',handles.panel_function,...
'Units','normalized',...
'BackgroundColor',[1 1 1],...
'Position',[0.02 0.24 0.79 0.25],...
'String',blanks(0),...
'Style','edit',...
'Tag','edit_fullFileName');


handles.button_browse = uicontrol(...
'Parent',handles.panel_function,...
'Units','normalized',...
'Position',[0.83 0.22 0.14 0.31],...
'String','Browse...',...
'Callback', @button_browse_Callback,...
'Tag','button_browse' );


handles.label_function = uicontrol(...
'Parent',handles.panel_function,...
'Units','normalized',...
'Position',[0.03 0.60 0.94 0.24],...
'String','Select the .m file that contains the function or GUI you wish to install as a module.',...
'Style','text',...
'Tag','label_function' );


handles.button_Install = uicontrol(...
'Parent',handles.main,...
'Units','normalized',...
'Position',[0.20 0.09 0.24 0.06],...
'String','Install',...
'Callback', @button_Install_Callback, ...
'Tag','button_Install' );


handles.button_Cancel = uicontrol(...
'Parent',handles.main,...
'Units','normalized',...
'Position',[0.52 0.09 0.24 0.06],...
'String','Cancel',...
'Callback', @button_cancel_Callback, ...
'Tag','button_Cancel');

handles.panel_parameters = uipanel(...
'Parent',handles.main,...
'Title','Module Parameters',...
'Clipping','on',...
'Position',[0.05 0.21 0.90 0.34],...
'Tag','panel_parameters');

handles.label_inputs = uicontrol(...
'Parent',handles.panel_parameters,...
'Units','normalized',...
'FontWeight','bold',...
'Position',[0.16 0.82 0.16 0.09],...
'String','Inputs',...
'Style','text',...
'Tag','label_inputs');


handles.listbox_inputs = uicontrol(...
'Parent',handles.panel_parameters,...
'Units','normalized',...
'BackgroundColor',[1 1 1],...
'Callback','',...
'FontName','fixedwidth',...
'FontSize',10,...
'HorizontalAlignment','left',...
'Position',[0.06 0.34 0.37 0.47],...
'Style','listbox',...
'Value',1,...
'Tag','listbox_inputs');


handles.button_inputs_comment = uicontrol(...
'Parent',handles.panel_parameters,...
'Units','normalized',...
'Position',[0.15 0.15 0.2 0.15],...
'String','Add Comment...',...
'Tag','button_inputs_comment');


handles.label_outputs = uicontrol(...
'Parent',handles.panel_parameters,...
'Units','normalized',...
'FontWeight','bold',...
'Position',[0.65 0.83 0.16 0.09],...
'String','Outputs',...
'Style','text',...
'Tag','label_outputs' );

handles.listbox_outputs = uicontrol(...
'Parent',handles.panel_parameters,...
'Units','normalized',...
'BackgroundColor',[1 1 1],...
'Callback','',...
'FontName','fixedwidth',...
'FontSize',10,...
'HorizontalAlignment','left',...
'Position',[0.56 0.34 0.37 0.47],...
'Style','listbox',...
'Value',1,...
'Tag','listbox_outputs');


handles.button_outputs_comment = uicontrol(...
'Parent',handles.panel_parameters,...
'Units','normalized',...
'Position',[0.65 0.15 0.2 0.15],...
'String','Add Comment...',...
'Tag','button_outputs_comment');

end